
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.2-node
      - image: cimg/mysql:8.0
    environment:
      - APP_ENV: testing
      - DB_CONNECTION: circle_test
      - MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

    steps:
      - checkout

      - run:
          name: Wait for MySQL
          command: |
            for i in `seq 1 30`; do
              nc -z mysql 3306 && break
              echo "Waiting for MySQL..."
              sleep 1
            done

      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libzip-dev unzip
            sudo docker-php-ext-install zip pdo_mysql
            
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run:
          name: Install Composer Dependencies
          working_directory: ~/project/src
          command: composer install --no-interaction --prefer-dist --optimize-autoloader

      - save_cache:
          paths:
            - vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
     
      - run:
          name: Run Tests
          working_directory: ~/project/src
          command: php artisan test

workflows:
  test:
    jobs:
      - build
