
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.2-node
      - image: cimg/mysql:8.0
    environment:
      APP_ENV: testing
      DB_CONNECTION: circle_test
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

    steps:
      - checkout

      - run:
          name: Wait for MySQL
          command: |
            for i in `seq 1 30`; do
              nc -z mysql 3306 && break
              echo "Waiting for MySQL..."
              sleep 1
            done

      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libzip-dev unzip
            sudo docker-php-ext-install zip pdo_mysql
            
      - run:
          name: Install Composer Dependencies
          working_directory: ~/project/src
          command: composer install --no-interaction --prefer-dist --optimize-autoloader
    
      - run:
          name: Run Tests
          working_directory: ~/project/src
          command: |
            php artisan storage:link
            php artisan test


  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:95yBb/qtbP31HqZ8J0yprFbvWbLKJlx+76iRWwU+uXY"

      - run:
          name: Deploy to EC2
          command: |
            ssh -vvv -o StrictHostKeyChecking=no ec2-user@3.26.230.133 "cd coachtech_flea_market/20240806_Flea_Market/ && git pull origin main && docker-compose -f docker-compose.prod.yml up -d"


workflows:
  test:
    jobs:
      - build
      - deploy:
          requires:
            - build
          # filters:
          #   branches:
          #       only: main
