version: 2.1

jobs:
  test:
    docker:
      - image: cimg/php:8.2-node
        environment:
          APP_ENV: test
          DB_CONNECTION: mysql_test
          DB_HOST: mysql
          DB_DATABASE: demo_test
          DB_USERNAME: 'root'
          DB_PASSWORD: 'root'
      - image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: demo_test

    steps:
      - checkout
      - setup_remote_docker:
          version: docker23
          docker_layer_caching: true
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/2.26.1/docker-compose-`uname -s`-`uname -m` > /tmp/docker-compose
            chmod +x /tmp/docker-compose
            /tmp/docker-compose --version
      - run:
          name: Check Docker Compose Version
          command: docker-compose --version
      - run:
          name: Setup Docker
          command: |
            # docker-compose -f docker-compose.dev.yml up mysql
            docker-compose -f docker-compose.dev.yml up php
            docker-compose exec -T php composer install
      - run:
          name: Setup Laravel
          command: |
            docker-compose exec -T php cp .env.example .env
            docker-compose exec -T php php artisan key:generate
      - run:
          name: Run Tests
          command: |
            docker-compose exec -T php vendor/bin/phpunit

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
