version: 2.1

jobs:
  test:
    docker:
      - image: cimg/php:8.2-node
      # - image: mysql:8.0
      #   environment:
      #     MYSQL_ROOT_PASSWORD: root
      #     MYSQL_DATABASE: demo_test

    steps:
      - checkout

      # - run:
      #     name: Wait for MySQL
      #     command: |
      #       for i in `seq 1 30`; do
      #         nc -z mysql 3306 && break
      #         echo "Waiting for MySQL..."
      #         sleep 1
      #       done

      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y libzip-dev unzip
            sudo docker-php-ext-install zip pdo_mysql
            
      - run:
          name: Install Composer Dependencies
          working_directory: ~/project/src
          command: composer install --no-interaction --prefer-dist --optimize-autoloader
     
      - run:
          name: Run Tests
          working_directory: ~/project/src
          command: php artisan test

workflows:
  version: 2
  test:
    jobs:
      - test