version: 2.1

jobs:
  test:
    docker:
      - image: cimg/php:8.2-node
        environment:
          APP_ENV: test
          DB_CONNECTION: mysql
          DB_HOST: mysql
          DB_DATABASE: demo_test
          DB_USERNAME: 'root'
          DB_PASSWORD: 'root'
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: demo_test
          MYSQL_USER: root
          MYSQL_PASSWORD: root

    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
      - run:
          name: Setup Docker
          command: |
            docker-compose -f docker-compose.dev.yml up --build -d
            docker-compose exec -T php composer install
      - run:
          name: Setup Laravel
          command: |
            docker-compose exec -T php cp .env.example .env
            docker-compose exec -T php php artisan key:generate
      - run:
          name: Run Tests
          command: |
            docker-compose exec -T php vendor/bin/phpunit

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
